config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "therapists", to: 'pages#index'
  get "patients", to: 'pages#patients'
  get "patient_appointments/:id", to: 'appointments#patient_appointments', as: :patient_appointments
  # get "visio", to: 'pages#visio'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   resources :appointments, only: [:index, :edit, :update] do
    resources :prescriptions, only: [:new, :create, :edit, :update]
    resources :feedbacks, only: [:index, :new, :create, :edit, :update]
    get "visio", to: 'pages#visio'
   end
  resources :prescriptions, only: :index
  # Path : donne la racine du chemin /therapists/
  # as : donne la dépendance /therapist_id
  resources :users, only: [:index, :show], :path => :therapists, as: :therapists do
    resources :appointments, only: [:new, :create, :show]
    resources :appointments, only: :destroy, as: :appointment_delete
    end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <footer class="footer-card">
    <div>
      <div class="d-flex justify-content-between">
      <div>
        <%= link_to root_path do %>
          <i class="icon fas fa-home"></i>
        <% end %>
      </div>

      <% if user_signed_in? && current_user.therapist == true %>
          <div>
            <%= link_to patients_path do %>
              <i class="icon fas fa-user-injured"></i>
            <% end %>
          </div>
      <% else %>
          <% if user_signed_in? %>
            <div>
              <%= link_to prescriptions_path do %>
                <i class="icon fas fa-pills"></i>
              <% end %>
            </div>
          <% else %>
            <div>
              <%= link_to new_user_session_path do %>
                <i class="icon fas fa-pills"></i>
              <% end %>
            </div>
          <% end %>
      <% end %>

      <% if user_signed_in? %>
        <div>
          <%= link_to appointments_path do %>
            <i class="icon fas fa-calendar-check"></i>
          <% end %>
        </div>
      <% else %>
        <div>
          <%= link_to new_user_session_path do %>
            <i class="icon fas fa-calendar-check"></i>
          <% end %>
        </div>
      <% end %>

      <div>
        <%= link_to therapists_path do %>
          <i class="icon fas fa-user-md"></i>
        <% end %>
      </div>

      </div>
    </div>
</footer>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="nav-login">
  <div>
    <%= link_to root_path, class: "navbar-brand" do %>
    <% if user_signed_in? %>
      <h2 class="hello">Bonjour,<br> <span class="user-name"><%= current_user.first_name %></span></h2>
    <% else %>
      <h2 class="hello">Bonjour</h2>
    <% end %>
    <% end %>
  </div>
  <div>
    <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link btn button-vert" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>


  <%# current_user.photo.key %>
  <%# image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier" %>