config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "therapists", to: 'pages#index'
  get "patients", to: 'pages#patients'
  get "patient_appointments/:id", to: 'appointments#patient_appointments', as: :patient_appointments
  # get "visio", to: 'pages#visio'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   resources :appointments, only: [:index, :edit, :update] do
    resources :prescriptions, only: [:new, :create, :edit, :update]
    resources :feedbacks, only: [:index, :new, :create, :edit, :update]
    get "visio", to: 'pages#visio'
   end
  resources :prescriptions, only: :index
  # Path : donne la racine du chemin /therapists/
  # as : donne la dépendance /therapist_id
  resources :users, only: [:index, :show], :path => :therapists, as: :therapists do
    resources :appointments, only: [:new, :create, :show]
    resources :appointments, only: :destroy, as: :appointment_delete
    end

end

app/views/pages/home.html.erb
<div class="container">
    <div class="card-appointment">
      <div class="card-appointment-text">
        <h5>Reserver une consultation avec votre therapeute :</h5>
      </div>
      <div class="card-appointment-search">
        <%= form_tag therapists_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a therapist"
          %>
          <%= submit_tag "Rechercher", class: "button-vert"%>
          <% end %>
      </div>
    </div>
    <% if user_signed_in? && current_user.therapist == false && Appointment.where(users_id: current_user.id).any? %>
    <br>
      <h3 class="h3_favorite_therapists">Mes therapeutes favoris</h3>
       <div class="container_favorite_therapists">
      <% @appointment_uniq.each do |appointment| %>
        <div class="container-index-therapist">
          <div class="therapist-card-index justify-content-between-index">
            <div class="card-product-favorite">
              <div class=""><%= cl_image_tag appointment.therapist.photo.key, crop: :fill %></div>
                <div class="card-product-infos text-end">
                  <h2 class="h2-card-therapist">
                    <strong><%= appointment.therapist.first_name %></strong>
                    <%= appointment.therapist.last_name %>
                  </h2>
                  <h4 class="h4-card-therapist">
                    <%= appointment.therapist.speciality %>
                  </h4>
                  <%= link_to 'Prendre un RDV', new_therapist_appointment_path(appointment.therapist), class:"form-button-favorite_therapists btn" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
</div>
  <div class="container">
    <div class="container-presentation">
      <h4>My Nath: <br> au service de votre santé</h4>
      <%= image_tag"https://res.cloudinary.com/lewagonss/image/upload/v1647429802/development/e293c03bd4b367efb62c_pmkdtd.svg" %>
      <p>Accédez <strong>rapidement</strong> aux disponibilités de tous vos professionnels de santé</p>
      <%= image_tag"https://res.cloudinary.com/lewagonss/image/upload/v1647429803/development/414f6d548cd8e7420ec2_get5kj.svg" %>
      <p>Prenez des décisions <strong>éclairées</strong> et adaptées à vos besoins de santé </p>
      <%= image_tag"https://res.cloudinary.com/lewagonss/image/upload/v1647429803/development/27df8684b01bff357f01_sw6quk.svg" %>
      <p>Gérez vos <strong>rendez-vous</strong> et <strong>documents</strong> de santé ainsi que ceux de vos proches sur une même application</p>
    </div>
  </div>
  <% else %>
    <div class="container">
      <div class="container-presentation">
        <h4>My Nath: <br> au service de votre santé</h4>
        <%= image_tag"https://res.cloudinary.com/lewagonss/image/upload/v1647429802/development/e293c03bd4b367efb62c_pmkdtd.svg" %>
        <p>Accédez <strong>rapidement</strong> aux disponibilités de tous vos professionnels de santé</p>
        <%= image_tag"https://res.cloudinary.com/lewagonss/image/upload/v1647429803/development/414f6d548cd8e7420ec2_get5kj.svg" %>
        <p>Prenez des décisions <strong>éclairées</strong> et adaptées à vos besoins de santé </p>
        <%= image_tag"https://res.cloudinary.com/lewagonss/image/upload/v1647429803/development/27df8684b01bff357f01_sw6quk.svg" %>
        <p>Gérez vos <strong>rendez-vous</strong> et <strong>documents</strong> de santé ainsi que ceux de vos proches sur une même application</p>
      </div>
    </div>
  <% end %>

app/views/pages/index.html.erb
  <% if @results.empty? %>
    <% @therapists.each do |therapist| %>
    <div class="container-index-therapist">
              <div class="therapist-card-index justify-content-between-index">
                <div class="card-product-index">
                  <div class=""><%= cl_image_tag therapist.photo.key, crop: :fill %></div>
                    <div class="card-product-infos text-end">
                    <h2 class="h2-card-therapist">
                      <strong><%= therapist.first_name%></strong>
                      <%= therapist.last_name%>
                    </h2>
                    <h4 class="h4-card-therapist">
                      <%= therapist.speciality %>
                    </h4>
                    <p class = "">
                    <% if user_signed_in?%>
                      <%= link_to 'Prendre un RDV', new_therapist_appointment_path(therapist), class:"form-button btn" %>
                    <% end %>
                    </p>
                    </span>
                  </div>
                  </div>
              </div>
            </div>

    <% end %>
  <% else  %>
    <div class="text-end"> <h4>Votre recherche : <span class="query">"<%= params[:query] %>"</span></h4>
      </div>
    <% @results.each do |therapist|%>
            <div class="container-index-therapist">
              <div class="therapist-card-index justify-content-between-index">
                <div class="card-product-index">
                  <div class=""><%= cl_image_tag therapist.photo.key, crop: :fill %></div>
                    <div class="card-product-infos text-end">
                    <h2 class="h2-card-therapist">
                      <strong><%= therapist.first_name%></strong>
                      <%= therapist.last_name%>
                    </h2>
                    <h4 class="h4-card-therapist">
                      <%= therapist.speciality %>
                    </h4>
                    <p class = "">
                    <% if user_signed_in?%>
                      <%= link_to 'Prendre un Rendez-Vous', new_therapist_appointment_path(therapist), class:"form-button btn" %>
                    <% end %>
                    </p>
                    </span>
                  </div>
                  </div>
              </div>
            </div>
     <% end %>
  <% end %>

app/views/pages/patients.html.erb
<div class="container mt-5 text-center">
  <h1 class="mb-3">Mes patients</h1>

  <% @appointment_uniq.each do |appointment| %>
       <%= link_to patient_appointments_path(appointment.user.id), class: "text-decoration-none" do %>
        <div class="d-flex">
          <div class="d-flex mt-1 listing">
          <h4 class="listing-elements"><%= appointment.user.last_name %> <%= appointment.user.first_name %></h4>
          </div>
        </div>
        <% end %>
      <% end %>

</div>

app/views/pages/visio.html.erb
<div class="consultation">
  <div
    class="twilio-video"
    data-sid="<%= ENV["ACCOUNT_SID"] %>"
    data-room="<%= @appointment.url_room %>"
    data-token="<%= @token %>"
    >
    <div class="participant"></div>
    <video id="userVideo" autoplay muted="true" ></video>
  </div>

  <div class="button-visio-center">
     <%  if current_user.therapist == true %>
    <button id='leave-btn' class='button-viso btn'><i class="fa-solid fa-phone-slash"></i></button>
    <div>
      <%= link_to 'Quittez', therapist_appointment_path(therapist_id: @appointment.therapist.id, id: @appointment.id), class: 'd-none root-link', data: {turbolinks: false}  %>
    </div>
      <%else%>
      <button id='leave-btn' class='button-viso btn'><i class="fa-solid fa-phone-slash"></i></button>
      <div>
      <%= link_to 'Quittez', prescriptions_path, class: 'd-none root-link', data: {turbolinks: false}   %>
    </div>
    <% end %>
  </div>
</div>