config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "therapists", to: 'pages#index'
  get "patients", to: 'pages#patients'
  get "patient_appointments/:id", to: 'appointments#patient_appointments', as: :patient_appointments
  # get "visio", to: 'pages#visio'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   resources :appointments, only: [:index, :edit, :update] do
    resources :prescriptions, only: [:new, :create, :edit, :update]
    resources :feedbacks, only: [:index, :new, :create, :edit, :update]
    get "visio", to: 'pages#visio'
   end
  resources :prescriptions, only: :index
  # Path : donne la racine du chemin /therapists/
  # as : donne la dépendance /therapist_id
  resources :users, only: [:index, :show], :path => :therapists, as: :therapists do
    resources :appointments, only: [:new, :create, :show]
    resources :appointments, only: :destroy, as: :appointment_delete
    end

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  require 'twilio-ruby'
  belongs_to :user, foreign_key: :users_id
  belongs_to :therapist, class_name: "User", foreign_key: :therapists_id
  has_many :prescriptions, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  before_create :set_room_name


  validates :date_time, presence: true
  validates :time, presence: true


  # callback ActiveRecord
  def set_room_name
    client = Twilio::REST::Client.new(ENV["ACCOUNT_SID"], ENV["API_KEY_SECRET"])
    room = client.video.rooms.create(unique_name: "#{self.users_id}_#{Time.now.to_i}")
    self.url_room = room.unique_name
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :time_frame, only: :new
  require 'twilio-ruby'

  def patient_appointments
    @user = User.find(params[:id])
    @patient_appointments = Appointment.where(users_id: @user)
    @therapist = current_user
    @appointments = @patient_appointments.where(therapists_id: @therapist)
    # @appointments_therapist = Appointment.where(therapists_id: current_user)

  end

  def index
    @user = current_user
    @appointments = Appointment.where(users_id: @user)
    @appointments_therapist = Appointment.where(therapists_id: current_user)
  end

  def show
    @therapist = User.find(params[:therapist_id])
    @user = current_user
  end

  def new
    @therapist = User.find(params[:therapist_id])
    @appointment = Appointment.new
    @user = current_user
    time_frame
  end

  def create
    @therapist = User.find(params[:therapist_id])
    @appointment = Appointment.new(appointment_params)
    @user = current_user
    @appointment.users_id = @user.id
    @appointment.therapists_id = @therapist.id
    if @appointment.save
      redirect_to therapist_appointment_path(@therapist, @appointment)
    else
      flash[:notice] = 'Erreur ! Selectionner un horaire'
      redirect_to new_therapist_appointment_path(@therapist)
    end

  end

  def edit
    time_frame
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to appointments_path, notice: 'Votre RDV est bien Mis à jour.'
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path, notice: 'Votre RDV est Annulé.'
  end

private

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:date_time, :time)
  end

  def time_frame
    @timeframe = [["09h00-10h00", Time.new(2022, 3, 26, 10, 0, 0, '+04:00')], ["10h00-11h00", Time.new(2022, 3, 26, 10, 0, 0, '+04:00')], ["11h00-12h00", Time.new(2022, 3, 26, 11, 0, 0, '+04:00')], ["14h00-15h00", Time.new(2022, 3, 26, 14, 0, 0, '+04:00')], ["15h00-16h00", Time.new(2022, 3, 26, 15, 0, 0, '+04:00')], ["16h00-17h00", Time.new(2022, 3, 26, 15, 0, 0, '+04:00')], ["17h00-18h00", Time.new(2022, 3, 26, 15, 0, 0, '+04:00')]]
  end


end

app/views/appointments/_form.html.erb
<div>
<%= simple_form_for ([@therapist, @appointment]), url: therapist_appointments_path, method: :post, remote: true do |f| %>
  <div class="tag-calendar">
  <%= f.date_field :date_time %>
  </div>
  <div class="radio-button">
  <%= f.input :time, label: "Choisissez votre créneau:", as: :radio_buttons, input_html: { class: "tag-selector" }, item_wrapper_class: 'tag-item', collection: @timeframe  %>
  </div>
  <%= f.button :submit, value: "Prendre votre RDV", class: "button-vert" %>
<% end %>
</div>

app/views/appointments/edit.html.erb
<div>
<%= simple_form_for (@appointment) do |f| %>
  <%= f.date_field :date_time, placeholder: @appointment.date_time %>
  <div class="radio-button">
  <%= f.input :time, label: "Choisissez votre créneau:", as: :radio_buttons, collection: @timeframe, :label_method => :last, :value_method => :first, priority: @appointment.time %>
  </div>

<%= f.button :submit, value: "Modifier votre RDV", class: "button-vert" %>
<% end %>
</div>

app/views/appointments/index.html.erb
<div class="container mt-5 text-center">
  <h1 class="mb-3">Vos consultations</h1>

  <% if @appointments.empty? && @appointments_therapist.empty? %>
    <h4>Vous n'avez pas encore de rendez-vous...</h4>
     <%= link_to "Cliquez-ici", therapists_path, class: "text-decoration-none" %>

  <% else %>
    <% if current_user.therapist == true %>
       <% @appointments_therapist.reverse_each do |appointment| %>
        <%= link_to therapist_appointment_path(therapist_id: appointment.therapist.id, id: appointment.id), class: "text-decoration-none" do %>
          <div class="d-flex">
            <div class="d-flex mt-1 listing">
            <h4 class="listing-elements"><%= appointment.user.last_name %> <%= appointment.user.first_name %></h4>
            <p class="listing-elements"><%= appointment.date_time.strftime("%d/%m/%y") %> <%= appointment.time.strftime("à %I:%M %p") %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <% @appointments.reverse_each do |appointment| %>
        <%= link_to therapist_appointment_path(therapist_id: appointment.therapist.id, id: appointment.id), class: "text-decoration-none" do %>
          <div class="d-flex">
            <div class="d-flex mt-1 listing">
            <h4 class="listing-elements"><%= appointment.therapist.last_name %> <%= appointment.therapist.first_name %></h4>
            <p class="listing-elements"><%= appointment.therapist.speciality %></p>
            <p class="listing-elements"><%= appointment.date_time.strftime("%d/%m/%y") %> <%= appointment.time.strftime("à %I:%M %p") %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
<% end %>
</div>

app/views/appointments/new.html.erb
<div class="container mt-5 text-center">
  <% if user_signed_in? %>
  <div class = "">
    <h2>Réservez votre Rendez-vous avec <%= @therapist.first_name %> </h2>
    <p></p>
  <% else %>
    <%=link_to "Please Log In", new_user_session_path %>
  <% end %>
  </div>


  <%= render 'form' %>

  


</div>

app/views/appointments/patient_appointments.html.erb
<div class="container mt-5 text-center">
  <h1 class="mb-3">Vos consultations</h1>

  <% if @appointments.empty? && @patient_appointments.empty? %>
    <h4>Vous n'avez pas encore de rendez-vous...</h4>
     <%= link_to "Cliquez-ici", therapists_path, class: "text-decoration-none" %>

  <% else %>
    <% if current_user.therapist == true %>
       <% @appointments.reverse_each do |appointment| %>
        <%= link_to therapist_appointment_path(therapist_id: appointment.therapist.id, id: appointment.id), class: "text-decoration-none" do %>
          <div class="d-flex">
            <div class="d-flex mt-1 listing">
            <h4 class="listing-elements"><%= appointment.user.last_name %> <%= appointment.user.first_name %></h4>
            <p class="listing-elements"><%= appointment.date_time.strftime("%d/%m/%y") %> <%= appointment.time.strftime("à %I:%M %p") %></p>
            </div>
          </div>
        <% end %>
      <% end %>
  <% end %>
<% end %>
</div>

app/views/appointments/show.html.erb
<div>
<br>
  <% if current_user.therapist == true %>
    <h2>Votre rendez-vous avec <%= @appointment.user.first_name %> <%= @appointment.user.last_name %> du <%= @appointment.date_time.strftime("%d/%m/%Y")%> <%= @appointment.time.strftime("à %I:%M %p") %> </h2>
    <%= link_to 'Accéder à votre consultation ', appointment_visio_path(@appointment), class:"button-vert" %>
  <div>
  <br>
    <% if @appointment.prescriptions.any? %>
      <% @appointment.prescriptions.each do |prescription|%>
        <h5 class="text-left"> Vos prescriptions : </h5>
        <div class="d-flex">
          <div class="d-flex mt-1 listing">
            <h4 class="listing-elements"><%= prescription.description %></h4>
              <p class="listing-elements"><%= prescription.appointment.therapist.first_name %> <%= prescription.appointment.therapist.last_name %></p>
              <p class="listing-elements">• <%= prescription.date %> •</p>
          <div class="listing-elements" >
            <%= link_to rails_blob_path(prescription.document, disposition: "attachment") do %>
            <i class="fa-solid fa-download fa-download-color-vert fa-lg"></i>
            <% end %>
          </div>
        </div>
       </div>
        <% end %>
      <% end %>
  </div>
    <%= link_to 'Ajouter une ordonnance', new_appointment_prescription_path(@appointment), class:"button-vert" %>
    <br>
    <%= link_to 'Feedbacks', appointment_feedbacks_path(@appointment), class:"button-vert" %>

  <% else %>

    <div class="card-appointment card-show-appointment">
      <% if DateTime.now.strftime("%d/%m/%Y") > @appointment.date_time.strftime("%d/%m/%Y") %>
        <h2>Recap' de votre rendez-vous</h2>
        <h4 class="p-show-appointment">Votre rendez-vous du <br> <%= @appointment.date_time.strftime("%d/%m/%Y")%> à <%= @appointment.time.strftime("%I:%M%p")%> <br> avec <%= @therapist.first_name %> <%= @therapist.last_name %></h4>
        <br>
        <%= link_to 'Ordonnances', prescriptions_path(@appointment), class:"button-vert" %>
        <%= link_to 'Feedbacks', appointment_feedbacks_path(@appointment), class:"button-vert" %>

      <% elsif DateTime.now.strftime("%d/%m/%Y") < @appointment.date_time.strftime("%d/%m/%Y") %>
          <h2>La marche à suivre</h2>
          <h4 class="p-show-appointment">Votre rendez-vous du <%= @appointment.date_time.strftime("%d/%m/%Y") %> à <%= @appointment.time.strftime("%I:%M%p")%> a bien été pris en compte avec <%= @therapist.first_name %> <%= @therapist.last_name %>.</h4>
          <br>
          <h4>Vous pourrez y accéder en temps voulu</h4>
          <%= link_to 'Assister à votre consultation', appointment_visio_path(@appointment), class:"button-vert" %>
          <br>
          <%= link_to 'Modifier RDV',  edit_appointment_path(@appointment), class:"button-vert" %>
          <%= link_to 'Annuler RDV',  therapist_appointment_delete_path(therapist_id: @appointment.therapist.id, id: @appointment.id), class:"button-vert", method: :delete, remote: true %>

      <% else %>
        <h2>C'est l'heure de votre rendez-vous !</h2>
         <%= link_to 'Assister à votre consultation', appointment_visio_path(@appointment), class:"button-vert" %>
      <% end %>
    </div>
  <% end %>
</div>